name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: | 
        cp /opt/devkitpro/devkitARM/arm-none-eabi/bin/* /opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/13.2.0/../../../../arm-none-eabi/bin
        git clone --recursive https://github.com/wtfloltk/picaGL
        cd picaGL
        make install
        cd ..
        git clone --recursive https://github.com/wtfloltk/imgui-picagl
        cd imgui-picagl
        make install
        cd ..
        chmod +x build_daedalus.sh
        ./build_daedalus.sh CTR_RELEASE
        mkdir build; cp daedbuild/*.cia build; cp daedbuild/*.3dsx build;
      
    - uses: actions/upload-artifact@master
      with:
        name: daedalusx64-3ds
        path: build
